app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
    resource: .
    type: uploader

dpo_edan:
    resource: "@DpoEdanBundle/Controller/"
    type:     annotation
    prefix:   /