security:
    # Preserve plain text password in token for refresh the user.
    # Analyze the security considerations before turn off this setting.
    erase_credentials: false

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: admin_home
                use_referer: true

            logout:
                target: /login
            anonymous:    true
            logout_on_user_change: true
            provider: fos_userbundle
